# Generated by Django 4.2.8 on 2026-05-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayapi', '0011_triviaquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='party',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='site_status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='pending_payment', max_length=20),
        ),
        migrations.AddField(
            model_name='party',
            name='subdomain',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('self_service', 'Self-Service ($99)'), ('guided', 'Guided ($229)'), ('full_service', 'Full Service ($399)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='birthdayapi.party')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#8B5CF6', max_length=7)),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7)),
                ('background_image_url', models.URLField(blank=True)),
                ('logged_in_background_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('template_id', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('elegant', 'Elegant'), ('playful', 'Playful'), ('minimalist', 'Minimalist')], default='classic', max_length=50)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('enable_photos', models.BooleanField(default=True)),
                ('enable_rsvp', models.BooleanField(default=True)),
                ('enable_games', models.BooleanField(default=True)),
                ('enable_gifts', models.BooleanField(default=True)),
                ('enable_guestbook', models.BooleanField(default=True)),
                ('enable_timeline', models.BooleanField(default=True)),
                ('welcome_message', models.CharField(default='Join us for an unforgettable celebration!', max_length=500)),
                ('rsvp_message', models.CharField(blank=True, max_length=500)),
                ('gift_message', models.CharField(blank=True, max_length=500)),
                ('thank_you_title', models.CharField(default='Thank You!', max_length=200)),
                ('thank_you_message', models.TextField(blank=True)),
                ('venmo_username', models.CharField(blank=True, max_length=100)),
                ('facebook_live_url', models.URLField(blank=True)),
                ('registry_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_config', to='birthdayapi.party')),
            ],
            options={
                'verbose_name': 'Site Config',
                'verbose_name_plural': 'Site Configs',
            },
        ),
    ]
