# Generated by Django 4.2.8 on 2026-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdayapi', '0012_party_custom_domain_party_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='thank_you_submessage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='theme',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='venue_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
